from PyQt6. QtWidgets import (QWidget, QApplication, QMainWindow, QTabWidget, QVBoxLayout, QHBoxLayout
                              ,QLineEdit, QToolButton, QLabel, QSizePolicy, QSpacerItem, QTableWidget
                              ,QTableWidgetItem)
import sys
from PyQt6.QtGui import QFont, QIcon, QPixmap
from PyQt6.QtCore import Qt , QSize, QMetaObject

class Ui_MainWindow(object):
    def setup_Ui(self, Form):
        Form.setObjectName('Form')
        Form.resize(900, 550)
        Form.setWindowTitle('Library Management System')
        self.centralWidget = QWidget(Form)
        self.centralWidget.setObjectName("centralWidget")
        Form.setCentralWidget(self.centralWidget)
        self.hBox = QHBoxLayout(self.centralWidget)
        self.tabWidget = QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.hBox.addWidget(self.tabWidget)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tabWidget.addTab(self.tab_1, "Issue Book")
        self.vBox_tab1 = QVBoxLayout(self.tab_1)
        self.horizontalWidget = QWidget(self.tab_1)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalWidget.setStyleSheet("QWidget {\n""\n""background-color:rgb(218,218,218)\n""\n""}")

        self.hBox_1 = QHBoxLayout(self.horizontalWidget)
        self.hBox_1.setObjectName("hBox_1")
        self.lineEdit_bookId = QLineEdit(self.horizontalWidget)
        self.lineEdit_bookId.setObjectName("lineEdit_bookId")
        self.lineEdit_bookId.setPlaceholderText("Please Enter Book Id ")
        self.hBox_1.addWidget(self.lineEdit_bookId)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.hBox_1.addItem(spacerItem)
        self.vBox_1 = QVBoxLayout()
        self.vBox_1.setObjectName("vBox_1")
        self.label_bookName = QLabel(self.horizontalWidget)
        self.label_bookName.setObjectName("label_bookName")
        self.label_bookName.setText("Book Name")
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_bookName.setFont(font)
        self.vBox_1.addWidget(self.label_bookName)
        self.label_bookAuthor = QLabel(self.horizontalWidget)
        self.label_bookAuthor.setObjectName("label_bookAuthor")
        self.label_bookAuthor.setText("Book Author")
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_bookAuthor.setFont(font)
        self.vBox_1.addWidget(self.label_bookAuthor)
        self.hBox_1.addLayout(self.vBox_1)

        self.vBox_tab1.addWidget(self.horizontalWidget)


        self.horizontalWidget_2 = QWidget(self.tab_1)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalWidget_2.setStyleSheet("QWidget {\n""\n""background-color:rgb(218,218,218)\n""\n""}")

        self.hBox_2 = QHBoxLayout(self.horizontalWidget_2)
        self.hBox_2.setObjectName("hBox_2")
        self.vBox_tab1.addWidget(self.horizontalWidget_2)
        self.lineEdit_memberId = QLineEdit(self.horizontalWidget_2)
        self.lineEdit_memberId.setObjectName("lineEdit_memberId")
        self.lineEdit_memberId.setPlaceholderText("Please Enter Member ID")
        self.hBox_2.addWidget(self.lineEdit_memberId)
        spacerItem_1 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.hBox_2.addItem(spacerItem_1)
        self.vBox_2 = QVBoxLayout()
        self.vBox_2.setObjectName("vBox_2")
        self.label_memberName = QLabel(self.horizontalWidget_2)
        self.label_memberName.setObjectName("label_memberName")
        self.label_memberName.setText("Member Name")
        self.vBox_2.addWidget(self.label_memberName)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_memberName.setFont(font)
        self.label_contactInfo = QLabel(self.horizontalWidget_2)
        self.label_contactInfo.setObjectName("label_contactInfo")
        self.label_contactInfo.setText("Contact Info")
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_contactInfo.setFont(font)
        self.vBox_2.addWidget(self.label_contactInfo)
        self.hBox_2.addLayout(self.vBox_2)
        self.vBox_tab1.addWidget(self.horizontalWidget_2)



        #button of tab1
        self.hBox_3 = QHBoxLayout()
        self.hBox_3.setObjectName("hBox_3")
        self.vBox_tab1.addLayout(self.hBox_3)
        spacerItem_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.hBox_3.addItem(spacerItem_2)
        self.button_issue = QToolButton(self.tab_1)
        self.button_issue.setObjectName("button_issue")
        self.button_issue.setText("Issue Book")
        icon = QIcon()
        icon.addPixmap(QPixmap("images/issuebook.png"))
        self.button_issue.setIcon(icon)
        self.button_issue.setIconSize(QSize(36, 36))
        self.button_issue.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        font = QFont()
        font.setPointSize(12)
        self.button_issue.setFont(font)
        self.hBox_3.addWidget(self.button_issue)
        spacerItem_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.hBox_3.addItem(spacerItem_3)
        self.vBox_tab1.addLayout(self.hBox_3)


        # tab2
        self.tab_2 = QWidget()
        self.tab_2.setObjectName("tab_2")
        self.vBox_tab2 = QVBoxLayout(self.tab_2)
        self.vBox_tab2.setObjectName("verticalLayout_6")
        self.lineEdit_submission = QLineEdit(self.tab_2)
        font = QFont()
        font.setPointSize(14)
        self.lineEdit_submission.setFont(font)
        self.lineEdit_submission.setStyleSheet("QLineEdit {\n""\n""background-color:rgb(218,218,218)\n""\n""}")
        self.lineEdit_submission.setObjectName("lineEdit_submission")
        self.lineEdit_submission.setText("Please Enter Book ID")
        self.vBox_tab2.addWidget(self.lineEdit_submission)
        self.tableWidget_bookinfo = QTableWidget(self.tab_2)
        font = QFont()
        font.setPointSize(12)
        self.tableWidget_bookinfo.setFont(font)
        self.tableWidget_bookinfo.setStyleSheet("QTableWidget {\n""\n""background-color:rgb(218,218,218)\n""\n""}")
        self.tableWidget_bookinfo.setObjectName("tableWidget_bookinfo")
        self.tableWidget_bookinfo.setColumnCount(4)
        self.tableWidget_bookinfo.setRowCount(0)
        item = QTableWidgetItem("Book ID")
        self.tableWidget_bookinfo.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem("Member ID")
        self.tableWidget_bookinfo.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem("Issue Time")
        self.tableWidget_bookinfo.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem("Renew Count")
        self.tableWidget_bookinfo.setHorizontalHeaderItem(3, item)
        self.tableWidget_bookinfo.horizontalHeader().setDefaultSectionSize(185)
        self.vBox_tab2.addWidget(self.tableWidget_bookinfo)
        self.hBox_4 = QHBoxLayout()
        self.hBox_4.setObjectName("hBox_4")
        spacerItem4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.hBox_4.addItem(spacerItem4)
        self.toolButton_renew = QToolButton(self.tab_2)
        font = QFont()
        font.setPointSize(12)
        self.toolButton_renew.setFont(font)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap("images/renew.png"), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButton_renew.setIcon(icon1)
        self.toolButton_renew.setIconSize(QSize(36, 36))
        self.toolButton_renew.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_renew.setObjectName("toolButton_renew")
        self.toolButton_renew.setText("Renew Book")
        self.hBox_4.addWidget(self.toolButton_renew)
        self.toolButton_submit = QToolButton(self.tab_2)
        font = QFont()
        font.setPointSize(12)
        self.toolButton_submit.setFont(font)
        icon2 = QIcon()
        icon2.addPixmap(QPixmap("images/submission.png"), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButton_submit.setIcon(icon2)
        self.toolButton_submit.setIconSize(QSize(36, 36))
        self.toolButton_submit.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_submit.setObjectName("toolButton_submit")
        self.toolButton_submit.setText("Submit Book")
        self.hBox_4.addWidget(self.toolButton_submit)
        spacerItem5 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding,QSizePolicy.Policy.Minimum)
        self.hBox_4.addItem(spacerItem5)
        self.vBox_tab2.addLayout(self.hBox_4)
        self.tabWidget.addTab(self.tab_2, "Renew/Submission Book")

        self.vBox = QVBoxLayout()
        self.vBox.setObjectName("vBox")
        self.hBox.addLayout(self.vBox)
        self.button_addBook = QToolButton(self.centralWidget)
        self.button_addBook.setObjectName("button_addBook")
        self.button_addBook.setText("Add Book")
        self.button_addBook.setMaximumSize(QSize(145, 90))
        font = QFont()
        font.setPointSize(12)
        self.button_addBook.setFont(font)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap("images/addbook.png"))
        self.button_addBook.setIcon(icon3)
        self.button_addBook.setIconSize(QSize(68,68))
        self.button_addBook.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.vBox.addWidget(self.button_addBook)

        self.button_addMember = QToolButton(self.centralWidget)
        self.button_addMember.setObjectName("button_addMember")
        self.button_addMember.setText("Add Member")
        self.button_addMember.setMaximumSize(QSize(145, 90))
        font = QFont()
        font.setPointSize(12)
        self.button_addMember.setFont(font)
        icon4 = QIcon()
        icon4.addPixmap(QPixmap("images/addmember.png"))
        self.button_addMember.setIcon(icon4)
        self.button_addMember.setIconSize(QSize(68, 68))
        self.button_addMember.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.vBox.addWidget(self.button_addMember)

        self.button_viewBooks = QToolButton(self.centralWidget)
        self.button_viewBooks.setObjectName("button_viewBook")
        self.button_viewBooks.setText("View Book")
        self.button_viewBooks.setMaximumSize(QSize(145, 90))
        font = QFont()
        font.setPointSize(12)
        self.button_viewBooks.setFont(font)
        icon5 = QIcon()
        icon5.addPixmap(QPixmap("images/viewbook .png"))
        self.button_viewBooks.setIcon(icon5)
        self.button_viewBooks.setIconSize(QSize(68, 68))
        self.button_viewBooks.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.vBox.addWidget(self.button_viewBooks)

        self.button_viewMembers = QToolButton(self.centralWidget)
        self.button_viewMembers.setObjectName("button_viewMembers")
        self.button_viewMembers.setText("View Members")
        self.button_viewMembers.setMaximumSize(145, 90)
        font= QFont()
        font.setPointSize(12)
        self.button_viewMembers.setFont(font)
        icon6 = QIcon()
        icon6.addPixmap(QPixmap("images/viewmembers.png"))
        self.button_viewMembers.setIcon(icon6)
        self.button_viewMembers.setIconSize(QSize(68 , 68))
        self.button_viewMembers.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.vBox.addWidget(self.button_viewMembers)




